micronaut:
  application:
    name: keyManagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 5
  channels:
    chavepix:
      address: ${GRPC_HOST:localhost}:50051
      plaintext: true
      max-retry-attempts: 5
